DROP TABLE DBAD03.CONTACTS;
COMMIT;
CREATE TABLE DBAD03.CONTACTS (
    ID INT GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LANG CHAR(2) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    MIDDLE_NAME VARCHAR(30),
    ADDL_NAME VARCHAR(30),
    EMAIL_ADDR VARCHAR(40) NOT NULL,
    LAST_CONTACT DATE,
    LAST_RESPONSE DATE,
    DO_NOT_CONTACT CHAR(1) DEFAULT NULL,
    CHECK (LANG = 'EN' OR LANG = 'ES'),
    CHECK (DO_NOT_CONTACT = 'X' OR DO_NOT_CONTACT = 'P')
) IN DATABASE INNOV;
